name: Oracle ARM Auto Provision

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run-macro:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install Dependencies
        run: composer install --no-dev --no-interaction

      - name: Create .env and Private Key
        run: |
          cat << 'KEYEOF' > ./oci_api_key.pem
          ${{ secrets.OCI_PRIVATE_KEY }}
          KEYEOF
          
          cat << ENVEOF > .env
          OCI_REGION=${{ secrets.OCI_REGION }}
          OCI_TENANCY_ID=${{ secrets.OCI_TENANCY_ID }}
          OCI_USER_ID=${{ secrets.OCI_USER_ID }}
          OCI_KEY_FINGERPRINT=${{ secrets.OCI_KEY_FINGERPRINT }}
          OCI_PRIVATE_KEY_FILENAME=./oci_api_key.pem
          OCI_SUBNET_ID=${{ secrets.OCI_SUBNET_ID }}
          OCI_IMAGE_ID=${{ secrets.OCI_IMAGE_ID }}
          OCI_COMPARTMENT_ID=${{ secrets.OCI_COMPARTMENT_ID }}
          ENVEOF

      - name: Run Oracle Macro
        run: php index.php
