name: Oracle ARM Auto Provision

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run-macro:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - run: composer install --no-dev --no-interaction

      - name: Create Private Key
        run: |
          printf '%s\n' '${{ secrets.OCI_PRIVATE_KEY }}' > ./oci_api_key.pem
          chmod 600 ./oci_api_key.pem

      - name: Create .env
        run: |
          {
            echo "OCI_REGION=${{ secrets.OCI_REGION }}"
            echo "OCI_TENANCY_ID=${{ secrets.OCI_TENANCY_ID }}"
            echo "OCI_USER_ID=${{ secrets.OCI_USER_ID }}"
            echo "OCI_KEY_FINGERPRINT=${{ secrets.OCI_KEY_FINGERPRINT }}"
            echo "OCI_PRIVATE_KEY_FILENAME=./oci_api_key.pem"
            echo "OCI_SUBNET_ID=${{ secrets.OCI_SUBNET_ID }}"
            echo "OCI_IMAGE_ID=${{ secrets.OCI_IMAGE_ID }}"
            echo "OCI_COMPARTMENT_ID=${{ secrets.OCI_COMPARTMENT_ID }}"
            echo "OCI_SHAPE=VM.Standard.A1.Flex"
            echo "OCI_OCPU=4"
            echo "OCI_MEMORY_IN_GBS=24"
            echo "OCI_SSH_PUBLIC_KEY=${{ secrets.OCI_SSH_PUBLIC_KEY }}"
          } > .env

      - name: Verify .env (debug)
        run: cat -A .env

      - name: Run Oracle Macro
        run: php index.php
